<!DOCTYPE html>
<html lang="ja-JP">
 <head>
  <meta charset="utf-8"/>
  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <meta content="Sample Description" name="description"/>
  <meta content="Yuichi Ito" name="author"/>
  <title>
   Python入門
  </title>
  <link href="/img/favicon.ico" rel="shortcut icon"/>
  <!-- Bootstrap -->
  <link href="./assets/css/bootstrap.css" rel="stylesheet">
   <link href="./assets/css/bootstrap-theme.css" rel="stylesheet"/>
   <link href="./assets/css/bootstrap_u1.css" rel="stylesheet"/>
   <!-- Font -->
   <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"/>
   <link href="https://fonts.googleapis.com/earlyaccess/mplus1p.css" rel="stylesheet">
    <!-- Code Highlight -->
    <link href="./assets/css/codehilite_colorful.css" rel="stylesheet"/>
    <!-- Custom -->
    <link href="./assets/css/font-awesome.min.css" rel="stylesheet"/>
    <link href="./assets/icomoon/style.css" rel="stylesheet"/>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
   </link>
  </link>
 </head>
 <body>
  <div class="backgroundLayer">
   <!-- Fixed navbar -->
   <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
     <div class="navbar-header">
      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggle collapsed" data-target="#navbar" data-toggle="collapse" type="button">
       <span class="sr-only">
        Toggle navigation
       </span>
       <span class="icon-bar">
       </span>
       <span class="icon-bar">
       </span>
       <span class="icon-bar">
       </span>
      </button>
      <a class="navbar-brand " href="./">
       Python
      </a>
     </div>
     <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav">
       <li class="">
        <a href="./navi.html">
         Navi
        </a>
       </li>
       <li class="">
        <a href="./qa.html">
         QA
        </a>
       </li>
       <li class="">
        <a href="./books.html">
         Books
        </a>
       </li>
       <li style="font-family: avenger">
        <a href="/">
         GC
        </a>
       </li>
      </ul>
     </div>
    </div>
   </nav>
   <div class="container">
    <div class="u1-header">
     <a href="./" style=" text-decoration: none;">
      <div class="u1-title">
       Python Boot Camp
      </div>
      <p class="lead u1-description">
       プログラミング言語Python訓練プログラム
      </p>
     </a>
    </div>
    <div class="row">
     <div class="col-sm-8 u1-main">
      <!-- GENERATED HTML START -->
      <!-- GENERATED HTML START -->
      <h1>
       高度な例外処理
      </h1>
      <div class="no_bullets" id="toc_container">
       <p class="toc_title">
        本記事の内容
       </p>
       <ul class="toc_list">
        <li>
         <a href="#header-1">
          概要
         </a>
        </li>
        <li>
         <a href="header-2">
          例外処理の場合分け
         </a>
        </li>
        <li>
         <a href="header-3">
          スタックトレース
         </a>
        </li>
        <li>
         <a href="header-4">
          traceback モジュール
         </a>
        </li>
        <li>
         <a href="header-5">
          キャッチした例外の丸投げ
         </a>
        </li>
       </ul>
      </div>
      <h2 id="header-1">
       概要
      </h2>
      <p>
       あとで書く
      </p>
      <h2 id="header-2">
       例外処理の場合分け
      </h2>
      <p>
       例外処理の文法は try except だけでなく、elseとfinallyがあります。
それぞれtryやexceptと同じような構文を持っており、その役割を簡単に説明すると以下のようになります。
      </p>
      <ul>
       <li>
        else: 例外が発生しなかった場合のみ処理される
       </li>
       <li>
        finally: 例外が発生してもしなくても処理される
       </li>
      </ul>
      <p>
       正直なところ、else と finally の使いどころはあまり多くないのですが、
elseは例外が発生しなかった場合の処理に使い、finallyは必ず実施したい処理がある場合に使います。
使いどころがなかなか難しく、私は「あえてこの処理をします」という表明の目的以外では両者を使いません。
      </p>
      <p>
       たとえば、オープンしたファイルをfinallyでクローズするということは言語を問わずよく実施されますが、
try/catchを抜けた箇所でのクローズでもだいたいカバーできます。
ただ、finallyにあえてクローズ処理を書くことで、「このtry/catchでファイルの資源を開放することを保証します」ということが、
ほかの人にも伝わるようになります。
      </p>
      <p>
       else と finally がどのように動くかコードで確認してみます。
テスト用のコードは以前利用したものとほぼ同じですが、今回はelseとfinallyが追加されています。
      </p>
      <div class="codehilite">
       <pre><span></span><span class="k">try</span><span class="p">:</span>
  <span class="k">print</span><span class="p">(</span><span class="s1">'1: start of try'</span><span class="p">)</span>
  <span class="mi">5</span> <span class="o">/</span> <span class="mi">0</span>
  <span class="k">print</span><span class="p">(</span><span class="s1">'2: end of try'</span><span class="p">)</span>

<span class="k">except</span> <span class="ne">Exception</span><span class="p">:</span>
  <span class="k">print</span><span class="p">(</span><span class="s1">'3: error happens'</span><span class="p">)</span>

<span class="k">else</span><span class="p">:</span>
  <span class="k">print</span><span class="p">(</span><span class="s2">"4: error doesn't happen"</span><span class="p">)</span>

<span class="k">finally</span><span class="p">:</span>
  <span class="k">print</span><span class="p">(</span><span class="s1">'5: finally'</span><span class="p">)</span>
</pre>
      </div>
      <p>
       注目して欲しいのは、例外が発生したあとにどの処理が実行されているかということです。とりあえず実行してみます。
      </p>
      <div class="codehilite">
       <pre><span></span># python3 test.py
1: start of try
3: error happens
5: finally
</pre>
      </div>
      <p>
       例外が発生して、exceptの処理とfinallyの処理が実行されていることがわかります。
一方 else の処理は実行されていないことも分かります。
次に、例外を発生させなくした場合です。0による除算をコメントアウトします。
      </p>
      <div class="codehilite">
       <pre><span></span><span class="k">try</span><span class="p">:</span>
  <span class="k">print</span><span class="p">(</span><span class="s1">'1: start of try'</span><span class="p">)</span>
  <span class="c1"># 5 / 0</span>
  <span class="k">print</span><span class="p">(</span><span class="s1">'2: end of try'</span><span class="p">)</span>

<span class="k">except</span> <span class="ne">Exception</span><span class="p">:</span>
  <span class="k">print</span><span class="p">(</span><span class="s1">'3: error happens'</span><span class="p">)</span>

<span class="k">else</span><span class="p">:</span>
  <span class="k">print</span><span class="p">(</span><span class="s2">"4: error doesn't happen"</span><span class="p">)</span>

<span class="k">finally</span><span class="p">:</span>
  <span class="k">print</span><span class="p">(</span><span class="s1">'5: finally'</span><span class="p">)</span>
</pre>
      </div>
      <p>
       これを実行すると以下のようになります。
      </p>
      <div class="codehilite">
       <pre><span></span># python3 test.py
1: start of try
2: end of try
4: error doesn't happen
5: finally
</pre>
      </div>
      <p>
       今度はexceptが呼ばれなくなり、代わりにelseが呼ばれています。
一方、finallyはまたもや呼ばれています。それほど複雑な動きではないと思うので、elseとfinallyの話はこのあたりで終わりとします 。
      </p>
      <h2 id="header-3">
       スタックトレース
      </h2>
      <p>
       try/exceptで例外をキャッチできることはわかりました。
ただ、やみくもに例外をキャッチするのは正直なところあまり行儀はよくないので、
「正しくエラーをキャッチ」してあげる必要があります。
たとえば、以下のコードがあるとしましょう。
      </p>
      <div class="codehilite">
       <pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="mi">5</span><span class="o">/</span><span class="mi">0</span>
    <span class="n">a</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span><span class="mi">2</span><span class="p">,</span><span class="mi">3</span><span class="p">]</span>
    <span class="k">print</span><span class="p">(</span><span class="n">a</span><span class="p">[</span><span class="mi">3</span><span class="p">])</span>

<span class="k">except</span> <span class="ne">Exception</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s1">'error happens'</span><span class="p">)</span>
</pre>
      </div>
      <p>
       このコードではいつものように5/0でエラーが起きますが、
それをコメントアウトしてもその後のリストの範囲外へのアクセスでエラーが発生します。
このコードには問題があるためエラーの発生自体は仕方がないのですが、このコードで問題となるのは以下の様な点です。
      </p>
      <ul>
       <li>
        はたして0除算とリストの範囲外へのアクセスを同等に扱うべきか
       </li>
       <li>
        そもそもこれは「例外処理」で対処するのではなくバグ修正すべき
       </li>
      </ul>
      <p>
       今回のような短いコードであればすぐに問題は見つかるかもしれませんが、
実際にはもっと長く複雑なコードがひとつのtryのカバー範囲になります。
そのため「何が原因で、どこでどのようなエラーが発生したのか」を正確に把握することは難しいです。
単にtry/catchを使うだけでなく、エラーの原因を把握できれば、「何を修正すべき」か、
「どのような例外クラスを使うべきか」がよくわかります。
      </p>
      <p>
       実はこの原因と問題の把握は、try/catchを利用していなければできていました。
たとえば上記コードのtry/catchを外して実行すると、5/0を実行した際に処理の中断とともに、
以下のようなエラー出力が得られてどこで何が発生していたのか一目でわかります。
      </p>
      <div class="codehilite">
       <pre><span></span>$ python3 test.py
Traceback <span class="o">(</span>most recent call last<span class="o">)</span>:
  File <span class="s2">"test.py"</span>, line <span class="m">1</span>, in &lt;module&gt;
    <span class="m">5</span>/0
ZeroDivisionError: division by zero
</pre>
      </div>
      <p>
       また、a[3]での範囲外のアクセスも以下のようにエラー原因が一目瞭然でわかります。
      </p>
      <div class="codehilite">
       <pre><span></span>$ python3 test.py
Traceback <span class="o">(</span>most recent call last<span class="o">)</span>:
  File <span class="s2">"test.py"</span>, line <span class="m">2</span>, in &lt;module&gt;
    a<span class="o">[</span><span class="m">3</span><span class="o">]</span>
IndexError: list index out of range
</pre>
      </div>
      <p>
       こういったエラー出力はスタックトレース(stack trace)と呼ばれていて、コードのどこでどういうふうに失敗したかを詳細に出力してくれます。もう少し詳細なトレースを見てみます。
以下のようなコードがあるとしましょう。分かりやすいように行数付きで書いています。
      </p>
      <div class="codehilite">
       <pre><span></span> 1    class A:
 2      def test(self, b):
 3        return b.div(0)
 4
 5    class B:
 6      def div(self, value):
 7        return 5/value
 8
 9    a = A()
10    b = B()
11    value = a.test(b)
</pre>
      </div>
      <p>
       このコードを実行すると最終的に 0 による割り算が発生してエラーとなってしまいます。実行すると以下のようなエラー出力が得られました。
      </p>
      <div class="codehilite">
       <pre><span></span>$ python3 test.py
Traceback <span class="o">(</span>most recent call last<span class="o">)</span>:
  File <span class="s2">"test.py"</span>, line <span class="m">11</span>, in &lt;module&gt;
    <span class="nv">value</span> <span class="o">=</span> a.test<span class="o">(</span>b<span class="o">)</span>
  File <span class="s2">"test.py"</span>, line <span class="m">3</span>, in <span class="nb">test</span>
    <span class="k">return</span> b.div<span class="o">(</span><span class="m">0</span><span class="o">)</span>
  File <span class="s2">"test.py"</span>, line <span class="m">7</span>, in div
    <span class="k">return</span> <span class="m">5</span>/value
ZeroDivisionError: division by zero
</pre>
      </div>
      <p>
       このエラーを上から読むと 11 行目で “value = a.test(b)” を実行し、3行目で” return b.div(0)” を実行し、
7 行目で “return 5/value” を実行し、そこで ZeroDivisionError となったことが分かります。
      </p>
      <h2 id="header-4">
       traceback モジュール
      </h2>
      <p>
       先ほど説明した「エラーを変数に格納し出力する」ことである程度の詳細を得ることは可能です。
ただ、より詳細を把握したい場合は traceback モジュールを使ってプログラムを停止することなくスタックトレースを取得すると便利です。
サンプルコードを以下に記載します。
      </p>
      <div class="codehilite">
       <pre><span></span><span class="kn">import</span> <span class="nn">traceback</span>

<span class="k">print</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
<span class="k">try</span><span class="p">:</span>
  <span class="k">print</span><span class="p">(</span><span class="mi">2</span><span class="p">)</span>
  <span class="mi">5</span><span class="o">/</span><span class="mi">0</span>
  <span class="k">print</span><span class="p">(</span><span class="mi">3</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span><span class="p">:</span>
  <span class="k">print</span><span class="p">(</span><span class="mi">4</span><span class="p">)</span>
  <span class="c1"># 文字列で取得</span>
  <span class="n">text</span> <span class="o">=</span> <span class="n">traceback</span><span class="o">.</span><span class="n">format_exc</span><span class="p">()</span>
  <span class="k">print</span><span class="p">(</span><span class="n">text</span><span class="p">)</span>
  <span class="c1"># ファイルに書き込み</span>
  <span class="n">f</span> <span class="o">=</span> <span class="nb">open</span><span class="p">(</span><span class="s1">'error.log'</span><span class="p">,</span> <span class="s1">'a'</span><span class="p">)</span>
  <span class="n">traceback</span><span class="o">.</span><span class="n">print_exc</span><span class="p">(</span><span class="nb">file</span><span class="o">=</span><span class="n">f</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span><span class="mi">5</span><span class="p">)</span>
</pre>
      </div>
      <p>
       上記では traceback モジュールの関数を2つ使っています。
ひとつめの format_exc() 関数はスタックトレースを文字列として返し、
2つめのprint_exc() は渡されたファイルオブジェクトにスタックトレースを書き込みます。
上記の実行結果は以下となります。
      </p>
      <div class="codehilite">
       <pre><span></span>$ python3 test.py
<span class="m">1</span>
<span class="m">2</span>
<span class="m">4</span>
Traceback <span class="o">(</span>most recent call last<span class="o">)</span>:
  File <span class="s2">"test.py"</span>, line <span class="m">6</span>, in &lt;module&gt;
    <span class="m">5</span>/0
ZeroDivisionError: division by zero

<span class="m">5</span>
</pre>
      </div>
      <p>
       また上記スタックトレースと同じ内容が書かれたファイルも作成されています。
プログラムの標準出力ではなくログファイルに出力する際にはこの機能を使うか、
もしくは logging モジュールを使ってエラーの文字列をファイルに書くのがよいと思います。
      </p>
      <h2 id="header-5">
       キャッチした例外の丸投げ
      </h2>
      <p>
       先に説明したraiseなのですが、もうひとつ別の使い方があります。
それは「exceptの中で呼び出すことで、エラーを呼び出し元で処理してもらう」というものです。
以下のコードを見てください。
      </p>
      <div class="codehilite">
       <pre><span></span><span class="k">def</span> <span class="nf">fun1</span><span class="p">():</span>
  <span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="ne">Exception</span><span class="p">(</span><span class="s1">'error in fun1()'</span><span class="p">)</span>
  <span class="k">except</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">"1: fun1 can't handle this error"</span><span class="p">)</span>
    <span class="c1"># 同じエラーを投げる</span>
    <span class="k">raise</span>

<span class="k">def</span> <span class="nf">fun2</span><span class="p">():</span>
  <span class="k">try</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s1">'2: call fun1'</span><span class="p">)</span>
    <span class="n">fun1</span><span class="p">()</span>
    <span class="k">print</span><span class="p">(</span><span class="s1">'3: done'</span><span class="p">)</span>
  <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s1">'4: catch error which happens in fun1()'</span><span class="p">)</span>
    <span class="k">print</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>

<span class="n">fun2</span><span class="p">()</span>
</pre>
      </div>
      <p>
       関数fun2()はfun1() をその内部で呼び出しています。
fun1() 内部でエラーを発生させて自ら except でそれを受け取っていますが、そのexceptの中でraiseをしています。
こうすると同じエラーが再発生するので、実質的に「呼び出し元に処理を依頼する」ことになります。
一応try/exceptでエラーをハンドルしようとしたけれども「ここでは対処しきれないエラーなので、
呼び出し元で例外処理をしてもらう」というような場合で同じエラーを再度 raise します。
      </p>
      <p>
       これを実行すると以下のような出力になります。
      </p>
      <div class="codehilite">
       <pre><span></span>$ python3 test.py
<span class="m">2</span>: call fun1
<span class="m">1</span>: fun1 can<span class="err">'</span>t handle this error
<span class="m">4</span>: catch error which happens in fun1<span class="o">()</span>
error in fun1<span class="o">()</span>
</pre>
      </div>
      <p>
       fun1() の中で再度 raise されたエラーを fun2() が受け取っているので、
例外のメッセージがオリジナルのもののままになっています。
なお、例外を処理しきれない場合は raise で同じものを再度発生させるのではなく別のエラーを raise させても構いません。
例えば適切なエラーメッセージに更新して再度 raise するというのはいいアイデアかもしれません。
      </p>
      <!-- GENERATED HTML END -->
      <!-- GENERATED HTML END -->
      <nav>
       <ul class="pager">
        <li id="previous-li">
         <a href="./119.html" id="previous-a">
          ← Previous
         </a>
        </li>
        <li>
         <a href="#">
          Page Top
         </a>
        </li>
        <li class="pager-next" id="next-li">
         <a href="./121.html" id="next-a">
          Next →
         </a>
        </li>
       </ul>
      </nav>
     </div>
     <!-- /.blog-main -->
     <div class="col-sm-3 col-sm-offset-1 u1-sidebar">
      <!-- SNS start -->
      <div class="sidebar-module">
       <ul class="social-buttons">
        <li>
         <!-- hatena -->
         <a class="hatena-bookmark-button" data-hatena-bookmark-lang="ja" data-hatena-bookmark-layout="basic-label-counter" href="http://b.hatena.ne.jp/entry/" title="このエントリーをはてなブックマークに追加">
          <img alt="このエントリーをはてなブックマークに追加" height="20" src="https://b.st-hatena.com/images/entry-button/button-only@2x.png" style="border: none;" width="20"/>
         </a>
         <script async="async" charset="utf-8" src="https://b.st-hatena.com/js/bookmark_button.js" type="text/javascript">
         </script>
        </li>
        <li>
         <!-- FB -->
         <div class="fb-like" data-action="like" data-layout="button_count" data-share="true" data-show-faces="false" data-size="small">
         </div>
         <div id="fb-root">
         </div>
         <script>
          (function(d, s, id) {
                    var js, fjs = d.getElementsByTagName(s)[0];
                    if (d.getElementById(id)) return;
                    js = d.createElement(s);
                    js.id = id;
                    js.src = "//connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.9";
                    fjs.parentNode.insertBefore(js, fjs);
                  }(document, 'script', 'facebook-jssdk'));
         </script>
        </li>
        <li>
         <!-- twitter -->
         <a class="twitter-share-button" href="https://twitter.com/share">
          Tweet
         </a>
         <script>
          ! function(d, s, id) {
                    var js, fjs = d.getElementsByTagName(s)[0],
                      p = /^http:/.test(d.location) ? 'http' : 'https';
                    if (!d.getElementById(id)) {
                      js = d.createElement(s);
                      js.id = id;
                      js.src = p + '://platform.twitter.com/widgets.js';
                      fjs.parentNode.insertBefore(js, fjs);
                    }
                  }(document, 'script', 'twitter-wjs');
         </script>
        </li>
        <li>
         <!-- G+ -->
         <!-- head 内か、body 終了タグの直前に次のタグを貼り付けてください。 -->
         <script async="" defer="" src="https://apis.google.com/js/platform.js">
          {
                    lang: 'ja'
                  }
         </script>
         <!-- 共有ボタン を表示したい位置に次のタグを貼り付けてください。 -->
         <div class="g-plus" data-action="share" data-annotation="none" data-height="24">
         </div>
        </li>
        <li>
         <!-- IN/Share -->
         <script src="//platform.linkedin.com/in.js" type="text/javascript">
          lang: ja_JP
         </script>
         <script data-counter="right" type="IN/Share">
         </script>
        </li>
       </ul>
      </div>
      <div class="print">
       <a href="./003_print.html">
        <img src="./assets/images/print.png"/>
        印刷する
       </a>
      </div>
      <!-- SNS end -->
      <div class="sidebar-module">
       <p class="sidebar-heading">
        Python入門
       </p>
       <ol class="list-unstyled">
        <li>
         <a href="./">
          トップページ
         </a>
        </li>
        <li>
         <a href="./navi.html">
          目次
         </a>
        </li>
        <li>
         <a href="./qa.html">
          質問と回答
         </a>
        </li>
        <li>
         <a href="./books.html">
          おすすめPython書籍
         </a>
        </li>
       </ol>
      </div>
      <div class="sidebar-module">
       <p class="sidebar-heading">
        初級編
       </p>
       <ol class="list-unstyled">
        <li>
         <a href="./001.html">
          Pythonプログラミング
         </a>
        </li>
        <li>
         <a href="./004.html">
          インストールと実行
         </a>
        </li>
        <li>
         <a href="./005.html">
          概要
         </a>
        </li>
        <li>
         <a href="./006.html">
          型と変数
         </a>
        </li>
        <li>
         <a href="./007.html">
          最重要な型
         </a>
        </li>
        <li>
         <a href="./008.html">
          制御構造
         </a>
        </li>
        <li>
         <a href="./009.html">
          関数
         </a>
        </li>
        <li>
         <a href="./010.html">
          モジュール
         </a>
        </li>
        <li>
         <a href="./011.html">
          オブジェクトとメソッド
         </a>
        </li>
        <li>
         <a href="./012.html">
          テキスト処理
         </a>
        </li>
        <li>
         <a href="./013.html">
          リスト再入門
         </a>
        </li>
        <li>
         <a href="./014.html">
          タプル
         </a>
        </li>
        <li>
         <a href="./015.html">
          セット
         </a>
        </li>
        <li>
         <a href="./016.html">
          辞書型
         </a>
        </li>
        <li>
         <a href="./017.html">
          None型
         </a>
        </li>
        <li>
         <a href="./018.html">
          ファイル処理
         </a>
        </li>
        <li>
         <a href="./019.html">
          基数と文字コード
         </a>
        </li>
        <li>
         <a href="./020.html">
          日本語の扱い
         </a>
        </li>
        <li>
         <a href="./021.html">
          プログラムへの入力
         </a>
        </li>
        <li>
         <a href="./022.html">
          関数の高度なトピック
         </a>
        </li>
        <li>
         <a href="./023.html">
          おわりに
         </a>
        </li>
       </ol>
      </div>
      <div class="sidebar-module">
       <p class="sidebar-heading">
        中級編
       </p>
       <ol class="list-unstyled">
        <li>
         <a href="./101.html">
          前書き
         </a>
        </li>
        <li>
         <a href="./102.html">
          目次
         </a>
        </li>
        <li>
         <a href="./103.html">
          オブジェクト指向を体験
         </a>
        </li>
        <li>
         <a href="./104.html">
          データ構造
         </a>
        </li>
        <li>
         <a href="./105.html">
          クラスとインスタンス化
         </a>
        </li>
        <li>
         <a href="./106.html">
          インスタンスとメソッド
         </a>
        </li>
        <li>
         <a href="./107.html">
          コンストラクタ
         </a>
        </li>
        <li>
         <a href="./108.html">
          self
         </a>
        </li>
        <li>
         <a href="./109.html">
          情報の隠蔽
         </a>
        </li>
        <li>
         <a href="./110.html">
          オブジェクトの役割
         </a>
        </li>
        <li>
         <a href="./111.html">
          関数型プログラミング
         </a>
        </li>
        <li>
         <a href="./112.html">
          ゲーム作り
         </a>
        </li>
        <li>
         <a href="./113.html">
          クラスの継承
         </a>
        </li>
        <li>
         <a href="./114.html">
          メソッドのオーバーライド
         </a>
        </li>
        <li>
         <a href="./115.html">
          GUIで継承を学ぶ
         </a>
        </li>
        <li>
         <a href="./116.html">
          クラスの高度なトピック
         </a>
        </li>
        <li>
         <a href="./117.html">
          ドキュメンテーション
         </a>
        </li>
        <li>
         <a href="./118.html">
          例外処理の基礎
         </a>
        </li>
        <li>
         <a href="./119.html">
          例外クラス
         </a>
        </li>
        <li>
         <a href="./120.html">
          高度な例外処理
         </a>
        </li>
        <li>
         <a href="./121.html">
          終わりに
         </a>
        </li>
       </ol>
      </div>
      <!-- amazon -->
      <div class="sidebar-module">
       <script type="text/javascript">
        amazon_ad_tag = "grit-22";
              amazon_ad_width = "300";
              amazon_ad_height = "250";
              amazon_ad_link_target = "new";
       </script>
       <script src="http://ir-jp.amazon-adsystem.com/s/ads.js">
       </script>
      </div>
      <!-- amazon end-->
      <div class="sidebar-module">
       <p class="sidebar-heading">
        Python入門
       </p>
       <ol class="list-unstyled">
        <li>
         <a href="https://github.com/yuichi110/www.yuichi.com-python" target="_blank">
          <span class="fa fa-github">
          </span>
          GitHub Repository
         </a>
        </li>
        <li>
         <a href="https://twitter.com/yuichi110" target="_blank">
          <i class="fa fa-twitter">
          </i>
          Twitter
         </a>
        </li>
        <li>
         <a href="https://www.linkedin.com/in/yuichiito/" target="_blank">
          <span class="fa fa-linkedin">
          </span>
          Linkedin (英語)
         </a>
        </li>
        <li class="li-none">
         <a href="#" id="rw_email_contact">
          <span class="fa fa-envelope">
           Mail
          </span>
         </a>
         <script type="text/javascript">
          var _rwObsfuscatedHref0 = "mai";
                  var _rwObsfuscatedHref1 = "lto";
                  var _rwObsfuscatedHref2 = ":yu";
                  var _rwObsfuscatedHref3 = "ich";
                  var _rwObsfuscatedHref4 = "i@y";
                  var _rwObsfuscatedHref5 = "uic";
                  var _rwObsfuscatedHref6 = "hi.";
                  var _rwObsfuscatedHref7 = "com";
                  var _rwObsfuscatedHref = _rwObsfuscatedHref0 + _rwObsfuscatedHref1 + _rwObsfuscatedHref2 + _rwObsfuscatedHref3 + _rwObsfuscatedHref4 + _rwObsfuscatedHref5 + _rwObsfuscatedHref6 + _rwObsfuscatedHref7;
                  document.getElementById("rw_email_contact").href = _rwObsfuscatedHref;
         </script>
        </li>
       </ol>
      </div>
      <div class="sidebar-module">
       <!-- padding for side bar -->
       <div class="hidden-xs">
        <p style="height:500px">
        </p>
       </div>
      </div>
     </div>
     <!-- /.blog-sidebar -->
    </div>
    <!-- /.row -->
   </div>
   <!-- /.container -->
   <footer>
    <div class="u1-footer-top">
    </div>
    <div class="u1-footer">
     <p>
      Copyright © 2017 Yuichi Ito All Rights Reserved.
     </p>
     <p align="center">
      修正依頼がある場合は右ページよりページURLと問題箇所を指摘願います。
      <a href="https://github.com/yuichi110/www.yuichi.com-python/issues">
       <span class="fa fa-github">
       </span>
       Git Hub Issues
      </a>
     </p>
    </div>
   </footer>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js">
   </script>
   <script src="./assets/js/bootstrap.min.js">
   </script>
   <script src="./assets/js/delete_useless_dom.js">
   </script>
   <!-- GOOGLE ANALYTICS -->
   <script>
    (function(i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function() {
          (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
          m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
      })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
      ga('create', 'UA-4830860-7', 'auto');
      ga('send', 'pageview');
   </script>
  </div>
  <!-- end of background -->
 </body>
</html>
